---
- name: Initial Setup of Cloud Instance
  hosts: localhost
  tasks:
    - name: Install epel-release
      register: result
      ansible.builtin.dnf:
        name: epel-release
        state: latest

    - name: Upgrade packages & repositories
      register: result
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install basic packages
      register: result
      ansible.builtin.dnf:
        name:
          - git
          - vim
          - zsh
          - net-tools
          - wget
          - htop
          - util-linux-user
          - tcpdump
          - wireguard-tools
          - tar
          - openssh-server
          - nfs-utils
          - wget
        state: latest

    - name: Start service sshd
      register: result
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started

    - debug:
        var: result.stdout_lines
