---
- name: Initial Setup of Cloud Instance
  hosts: localhost
  tasks:
    - name: Install epel-release
      register: result
      ansible.builtin.dnf:
        name: epel-release
        state: latest
    - debug: var=result

    - name: Upgrade packages & repositories
      register: result
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - debug: var=result

    - name: Install basic packages
      register: result
      ansible.builtin.dnf:
        name:
          - git
          - vim
          - zsh
          - net-tools
          - wget
          - htop
          - util-linux-user
          - tcpdump
          - wireguard-tools
          - tar
          - openssh-server
          - nfs-utils
          - wget
        state: latest
    - debug: var=result

    - name: Start service sshd
      register: result
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started
    - debug: var=result

    - name: Configure zsh, zimfw and p10k
      register: result
      ansible.builtin.shell:
        cmd: |
          chsh -s /usr/bin/zsh
          wget -nv -O - https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
          echo "zmodule romkatv/powerlevel10k --use degit" >> ~/.zimrc
          zsh -s "zimfw install"
    - debug: var=result
